=== ksassenberg/datagen/src/main/resources/com/fenergo/fdim/datagen/xsd/Configuration.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" targetNamespace="http://com.fenergo.fdim/Configuration" 
	xmlns:tns="http://com.fenergo.fdim/Configuration" 
	xmlns:enums="http://com.fenergo.fdim/ConfigEnums"
	elementFormDefault="qualified">

	<xs:import namespace="http://com.fenergo.fdim/ConfigEnums" schemaLocation="./ConfigEnums.xsd"/>

	<xs:element name="Configuration" type="tns:ConfigurationType"/>

	<xs:complexType name="ConfigurationType">
	  <xs:sequence>
	    <xs:element name="output_file" type="xs:string" minOccurs="1" maxOccurs="1"/>
	    <xs:element name="batch_size" type="xs:long" minOccurs="1" maxOccurs="1"/>
	    <xs:element name="root_entities" type="tns:ListOfRootEntityType" minOccurs="1" maxOccurs="1"/>
	  </xs:sequence>
	</xs:complexType>
	
	<xs:complexType name="ListOfRootEntityType">
	  <xs:sequence>
	    <xs:element name="root_entity" type="tns:RootEntityType" minOccurs="1" maxOccurs="unbounded"/>
	  </xs:sequence>
	</xs:complexType>
	
	<xs:complexType name="RootEntityType">
	  <xs:complexContent>
            <xs:extension base="tns:AbstractEntityType">
            	<xs:sequence>
	    			<xs:element name="child_entities" type="tns:ListOfChildEntityType" minOccurs="0" maxOccurs="1"/>
	  			</xs:sequence>
            </xs:extension>
       </xs:complexContent>
	</xs:complexType>
	
	<xs:complexType name="ListOfChildEntityType">
	  <xs:sequence>
	    <xs:element name="child_entity" type="tns:ChildEntityType" minOccurs="1" maxOccurs="unbounded"/>
	  </xs:sequence>
	</xs:complexType>
	
	<xs:complexType name="ChildEntityType">
	  <xs:complexContent>
            <xs:extension base="tns:AbstractEntityType"/>
       </xs:complexContent>
	</xs:complexType>
	
	 <xs:complexType name="AbstractEntityType" abstract="true">
        <xs:sequence>
            <xs:element name="type" type="enums:EntityType" minOccurs="1" maxOccurs="1"/>
            <xs:element name="occurences" type="xs:long" minOccurs="1" maxOccurs="1"/>
            <xs:element name="cache_size" type="xs:long" minOccurs="1" maxOccurs="1"/>
        </xs:sequence>
    </xs:complexType>

</xs:schema>

=== ksassenberg/datagen/src/main/resources/com/fenergo/fdim/datagen/config/xml/configuration.xml
<?xml version="1.0" encoding="UTF-8"?>
<tns:Configuration xmlns:enums="http://com.fenergo.fdim/ConfigEnums" 
	xmlns:tns="http://com.fenergo.fdim/Configuration"
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" 
	xsi:schemaLocation="http://com.fenergo.fdim/Configuration ../../xsd/Configuration.xsd http://com.fenergo.fdim/ConfigEnums ConfigEnums.xsd ">
  
	<tns:output_file>C:\Users\User\Desktop\output.xml</tns:output_file>
	<tns:batch_size>1000</tns:batch_size>
	<tns:root_entities>
		<tns:root_entity>
			<tns:type>LegalEntity</tns:type>
			<tns:occurences>10000</tns:occurences>
			<tns:child_entities>
				<tns:child_entity>
					<tns:type>Contact</tns:type>
      				<tns:occurences>1</tns:occurences>
      			</tns:child_entity>
		      	<tns:child_entity>
			      	<tns:type>Address</tns:type>
			      	<tns:occurences>1</tns:occurences>
			      	</tns:child_entity>
		      	<tns:child_entity>
			      	<tns:type>Association</tns:type>
			      	<tns:occurences>1</tns:occurences>
			      </tns:child_entity>
		      	<tns:child_entity>
			      	<tns:type>Relationship</tns:type>
			      	<tns:occurences>1</tns:occurences>
			 	</tns:child_entity>
  			</tns:child_entities>
    	</tns:root_entity>
		<tns:root_entity>
  			<tns:type>User</tns:type>
  			<tns:occurences>1000</tns:occurences>
		</tns:root_entity>
		<tns:root_entity>
  			<tns:type>Lookup</tns:type>
  			<tns:occurences>10000</tns:occurences>
		</tns:root_entity>
  	</tns:root_entities>
</tns:Configuration>
